### PR TITLE
fix linking

### PR DESCRIPTION
**Pull request by glensc**
link libafdt with libevent

### CODE REVIEW

**Comment by dreiss** [comment]
Could this ever cause the objects from libevent.a to be added into libafdt.a?

**Comment by glensc** [comment]
i don't think so, `ar` command adds just `.o` from current build:

```
libtool: link: ar cru .libs/libafdt.a  util.o lowlevel.o sync.o strlcpy.o async.o
libtool: link: ranlib .libs/libafdt.a
```

here's `libafdt.a` built with above patch applied:

```
$ ar tvf /usr/lib64/libafdt.a
rw-r--r-- 1000/1000   2792 May 16 16:27 2010 util.o
rw-r--r-- 1000/1000   4744 May 16 16:27 2010 lowlevel.o
rw-r--r-- 1000/1000   2552 May 16 16:27 2010 sync.o
rw-r--r-- 1000/1000   1120 May 16 16:27 2010 strlcpy.o
rw-r--r-- 1000/1000   6984 May 16 16:27 2010 async.o
```

**Comment by glensc** [comment]
any progress?

**Comment by dreiss** [comment]
Sorry I dropped this.  I put a little more information in the commit message and pushed this as 5c3f936480f7efea6734cf9940d57fdf255950ed

**Comment by glensc** [comment]
thanks!

**Pull request closed without merging**
